if [ -f ~/.dir_colors ]; then
    eval `dircolors ~/.dir_colors`
fi

complete -cf sudo

vman() {
   vim -c "SuperMan $*"

   if [ "$?" != "0" ]; then
  	 echo "No manual entry for $*"
   fi
}


function colour_my_prompt {
    local BRed='\[\e[1;31m\]'
    local Red='\[\e[0;31m\]'
    local Red='\[\e[0;31m\]'
    local BBlue='\[\e[1;34m\]'
    local BBlue='\[\e[1;34m\]'
    local Green='\[\e[0;32m\]'
    local BGreen='\[\e[1;32m\]'
    local BYellow='\[\e[1;49;93m\]'
    local NC='\[\e[m\]'
    local __host="${Red}\h"
    local __separator="::"
    local __curr_location="${BBlue}\W"
    #local __end_prompt="${BGreen}> "
    local __end_prompt="${BGreen}ᐅ  "
    local __reset_color="${NC}"
    export PS1="$__host$__separator$__curr_location $__end_prompt$__reset_color"
}

colour_my_prompt

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

alias ls='ls --color=auto'
source /home/shagai/.bazel/bin/bazel-complete.bash

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:/usr/bin"

export CUDA_HOME=/opt/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib"
export PATH="$CUDA_HOME/bin:$PATH"

export OPENAI_GYM_API_KEY=sk_4WYhUBanSJ1HiPocUAOWw

export VISUAL="vim"
# export TERM=screen-256color

export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
